packages:
  - "packages/*"
  - "apps/*"
  - "examples/*"
injectWorkspacePackages: true
syncInjectedDepsAfterScripts:
  - build
supportedArchitectures:
  os:
    - current
    - linux
  cpu:
    - current
    - x64
allowBuilds:
  "@embedded-postgres/darwin-arm64": true
  "@embedded-postgres/darwin-x64": true
  "@embedded-postgres/linux-arm64": true
  "@embedded-postgres/linux-x64": true
  "@embedded-postgres/windows-x64": true
  cpu-features: false
  esbuild: true
  protobufjs: false
  ssh2: false
  vue-demi: true
