apiVersion: v1
kind: Service
metadata:
  name: {{ include "prism.fullname" . }}
  labels:
    {{- include "prism.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "prism.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.http.port }}
      targetPort: http
      protocol: TCP
